[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "team-systematics"
version = "1.0"

[project.optional-dependencies]
test = [
    "pytest",
    "httpx",
]

[tool.setuptools.packages.find]
where = ["src"]
