services:
  db:
    image: postgres:15-alpine
    container_name: my_postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  postgres_data: